x = input('Escreva algo: ')
print('O tipo dele é: ', type(x))
print('Esta em caixa alta? {}'.format(x.isupper()))
print('Ele é alfabetico?', x.isalpha())
print('Ele é alfabetico e numerico?', x.isalnum())
print('Ele esta em caixa baixa?', x.islower())
print('Ele é decimal?', x.isdecimal())
print('Contem espaço?', x.isspace())
print('É numerico?', x.isnumeric())
print('Esta capitalizada? ', x.istitle())
