sal = float(input('Coloque o salario do funcionario: R$'))
print('O salario do funcionario com 15% de aumento é: {:.2f}'.format(sal+(sal * 15/100)))
aumento = sal + (sal * 15/100)
print('O salario do funcionario com 15% de aumento é: {:.2f}'.format(aumento))
print('\n\n')
produto = float(input('Coloque o valor do produto: R$'))
parcelado = produto + (produto * 8/100)
vista = produto - (produto * 10/100)
print('O preço parcelado é R${} e o preço do produto a vista é R${}'.format(parcelado, vista))
